language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install:
- npm install

deploy:
  provider: heroku
  api_key:
    secure: ${HEROKU_API_KEY}
  skip_cleanup: true
  app: class-management-101
